### ISSUE TITLE
ENOENT for converted .png

### ISSUE THREAD

**Issue by RsknCankov** [marcdacz/chai-pdf#1]
Hello, 
I'm making a basic pdf comparison of two files.
Test fails with following error:
  AssertionError: expected 'baseLinePdf.pdf' to be same pdf as generatedpdf.pdf'
[{"result":"failed","actual":"/opt/app/data/actualPngs/base-pdf-BASKET/base-pdf-BASKET-0.png","error":{"errno":-2,"syscall":"open","code":"ENOENT","path":"/opt/app/data/actualPngs/base-pdf-BASKET/base-pdf-BASKET-0.png"}}]

It seems like it looking for the file with suffix of the index, however there is a png file generated without suffix of "-0" in the following dir. 

I also edited the index.js of the library to created .png without suffixing the index and it seems to working just fine

**Comment by marcdacz** [comment]
Hi, 

Firstly, thanks for using the plugin. Really appreciate your feedback as well.
May I know which line have you changed as I am wondering why wouldn't it generate an index as each page is indexed.

**Comment by RsknCankov** [comment]
Hi there,
Here is the 'data' folder structure after tests is being run by following lines:
await expect('base-pdf-BASKET.pdf').to.be.samePdfAs('base-pdf-BASKET.pdf');
await expect('base-pdf-weight-generated.pdf').to.be.samePdfAs('base-pdf-WEIGHT.pdf');

![image](https://user-images.githubusercontent.com/6483181/72793131-8506f800-3c53-11ea-9023-f29edfeaae53.png)

Locally when I change these lines:
            let actualPng = `${actualPngDirPath}/${actualPdfBaseName}-${index}.png`;
            let baselinePng = `${baselinePngDirPath}/${baselinePdfBaseName}-${index}.png`;
            let diffPng = `${diffPngDirPath}/${actualPdfBaseName}_diff-${index}.png`;
To:
            let actualPng = `${actualPngDirPath}/${actualPdfBaseName}.png`;
            let baselinePng = `${baselinePngDirPath}/${baselinePdfBaseName}.png`;
            let diffPng = `${diffPngDirPath}/${actualPdfBaseName}_diff.png`;

It manages to find the generated png.

**Comment by marcdacz** [comment]
Hi,

Thanks for providing me with those inputs. I have found the culprit. Apparently, indexes are not added for single page pdfs. Unfortunately, I missed this one but thanks to you I have fixed it now in v1.0.8. I've also added tests for this. Please download the latest and confirm if it did fix the issue. Let me know so we can close this one.

Anyway, if you need more advanced pdf comparison, I've made another node module, this time a standalone one: https://www.npmjs.com/package/compare-pdf
I am hoping you can check that out.

Again, thanks for using the plugin and keep in touch!

**Comment by RsknCankov** [comment]
Just tested version 1.0.8. WORKED fine thank you man. Really appreciate fast response, this affect directly my deadline... Cheers!

**Comment by marcdacz** [comment]
Happy to help mate!
