### ISSUE TITLE
.git folder exist in module folder causing npm ERR!

### ISSUE THREAD

**Issue by RsknCankov** [marcdacz/chai-pdf#2]
Hi there, 
seem like .git folder is in the module folder which causes following ERR:
npm ERR! path /opt/atlassian/pipelines/agent/build/node_modules/chai-pdf
npm ERR! code EISGIT
npm ERR! git /opt/atlassian/pipelines/agent/build/node_modules/chai-pdf: Appears to be a git repo or submodule.
npm ERR! git     /opt/atlassian/pipelines/agent/build/node_modules/chai-pdf
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

**Comment by marcdacz** [comment]
Hi,

Apologies for this one. In my rush to publish I missed the .git folder.
Anyway, I've published v1.0.9.
Please download then try again.

Again, apologies and thanks for reporting the issue.

**Comment by marcdacz** [comment]
By the way, to fix it in your current project, navigate to /node_modules/chai-pdf and delete the .git folder. This will now allow you to upgrade to the new version. 
Again, apologies for the inconvenience.
